name: Build and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Python for node-gyp (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Configure Windows build tools
        if: matrix.os == 'windows-latest'
        run: |
          npm config set cache C:\npm-cache
          npm config set target_platform win32
          npm config set target_arch x64

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          npm install --no-audit --no-fund --legacy-peer-deps
        env:
          ELECTRON_CACHE: C:\electron-cache

      - name: Install dependencies (Non-Windows)
        if: matrix.os != 'windows-latest'
        run: npm ci --no-audit --no-fund

      - name: Build application and Electron app (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          # Set environment variables
          $env:ELECTRON_CACHE = "C:\electron-cache"
          $env:CSC_IDENTITY_AUTO_DISCOVERY = "false"

          # Create cache directory
          New-Item -ItemType Directory -Force -Path "C:\electron-cache" | Out-Null

          # Kill any running node processes
          Get-Process -Name "node" -ErrorAction SilentlyContinue | Stop-Process -Force
          Start-Sleep -Seconds 2

          # Clean previous build
          if (Test-Path "dist") { Remove-Item -Recurse -Force "dist" }

          # Build application
          Write-Host "Building TypeScript..."
          npx tsc -p tsconfig.json
          if ($LASTEXITCODE -ne 0) { throw "TypeScript build failed" }

          Write-Host "Copying assets..."
          npm run copy:assets
          if ($LASTEXITCODE -ne 0) { throw "Asset copy failed" }

          Write-Host "Building CSS..."
          npm run tailwind:build
          if ($LASTEXITCODE -ne 0) { throw "CSS build failed" }

          Write-Host "Building Electron app..."
          npx electron-builder --win
          if ($LASTEXITCODE -ne 0) { throw "Electron build failed" }

          Write-Host "Build completed successfully!"
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build application (Non-Windows)
        if: matrix.os != 'windows-latest'
        run: npm run build

      - name: Build Electron app (Non-Windows)
        if: matrix.os != 'windows-latest'
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            dist/*.exe
            dist/*.zip

      - name: Upload artifacts (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            dist/*.dmg
            dist/*.zip

      - name: Upload artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            dist/*.AppImage
            dist/*.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -la artifacts/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.version }}-${{ github.run_number }}
          release_name: Release v${{ steps.package-version.outputs.version }}-${{ github.run_number }}
          body: |
            Auto-generated release from commit ${{ github.sha }}

            ## Changes
            - Latest changes from commit: ${{ github.event.head_commit.message }}

            ## Downloads
            Choose the appropriate version for your operating system:
            - **Windows**: `.exe` (installer) or `.zip` (portable)
            - **macOS**: `.dmg` (installer) or `.zip` (portable)  
            - **Linux**: `.AppImage` (portable) or `.deb` (Debian/Ubuntu)
          draft: false
          prerelease: false

      - name: Upload Windows NSIS installer
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/windows-artifacts/One Chat App Setup ${{ steps.package-version.outputs.version }}.exe
          asset_name: OneChat-Setup-${{ steps.package-version.outputs.version }}.exe
          asset_content_type: application/octet-stream
        continue-on-error: true

      - name: Upload Windows ZIP
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/windows-artifacts/One Chat App-${{ steps.package-version.outputs.version }}-win.zip
          asset_name: OneChat-${{ steps.package-version.outputs.version }}-windows.zip
          asset_content_type: application/zip
        continue-on-error: true

      - name: Upload macOS DMG
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/macos-artifacts/One Chat App-${{ steps.package-version.outputs.version }}.dmg
          asset_name: OneChat-${{ steps.package-version.outputs.version }}.dmg
          asset_content_type: application/octet-stream
        continue-on-error: true

      - name: Upload macOS ZIP
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/macos-artifacts/One Chat App-${{ steps.package-version.outputs.version }}-mac.zip
          asset_name: OneChat-${{ steps.package-version.outputs.version }}-macos.zip
          asset_content_type: application/zip
        continue-on-error: true

      - name: Upload Linux AppImage
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/linux-artifacts/One Chat App-${{ steps.package-version.outputs.version }}.AppImage
          asset_name: OneChat-${{ steps.package-version.outputs.version }}.AppImage
          asset_content_type: application/octet-stream
        continue-on-error: true

      - name: Upload Linux DEB
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/linux-artifacts/one-chat-app_${{ steps.package-version.outputs.version }}_amd64.deb
          asset_name: OneChat-${{ steps.package-version.outputs.version }}.deb
          asset_content_type: application/vnd.debian.binary-package
        continue-on-error: true
